// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.github.mgljava.protobuf_grpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:guide.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   */
  String getRealname();
  /**
   * <code>string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
