// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.github.mgljava.protobuf_grpc;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:guide.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
