// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.github.mgljava.protobuf_grpc;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_guide_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_guide_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_guide_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_guide_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_guide_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_guide_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_guide_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_guide_StudentRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\005guide\"\035\n\tMyRequest\022\020\n\010u" +
      "sername\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010realname\030" +
      "\001 \001(\t\"=\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022\013" +
      "\n\003age\030\002 \001(\005\022\017\n\007address\030\003 \001(\t\"\035\n\016StudentR" +
      "equest\022\013\n\003age\030\001 \001(\0052\237\002\n\016StudentService\022>" +
      "\n\025getRealNameByUsername\022\020.guide.MyReques" +
      "t\032\021.guide.MyResponse\"\000\022<\n\021getStreamRealN" +
      "ame\022\020.guide.MyRequest\032\021.guide.MyResponse" +
      "\"\0000\001\022E\n\020GetStudentByAges\022\025.guide.Student" +
      "Request\032\026.guide.StudentResponse\"\000(\001\022H\n\021G" +
      "etStudentsByAges\022\025.guide.StudentRequest\032" +
      "\026.guide.StudentResponse\"\000(\0010\001B+\n\031com.git" +
      "hub.mgljava.proto3B\014StudentProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_guide_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_guide_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_guide_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_guide_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_guide_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_guide_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_guide_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_guide_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_guide_StudentResponse_descriptor,
        new String[] { "Name", "Age", "Address", });
    internal_static_guide_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_guide_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_guide_StudentRequest_descriptor,
        new String[] { "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
