// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.github.mgljava.protobuf_grpc;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:guide.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string address = 3;</code>
   */
  String getAddress();
  /**
   * <code>string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
