// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/grpc/route_guide.proto

package com.github.mgljava.grpc;

public interface FeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.FeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  java.util.List<com.github.mgljava.grpc.Feature> 
      getFeatureList();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  com.github.mgljava.grpc.Feature getFeature(int index);
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  java.util.List<? extends com.github.mgljava.grpc.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .routeguide.Feature feature = 1;</code>
   */
  com.github.mgljava.grpc.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
