// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/grpc/route_guide.proto

package com.github.mgljava.grpc;

public interface RectangleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Rectangle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  boolean hasLo();
  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  com.github.mgljava.grpc.Point getLo();
  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  com.github.mgljava.grpc.PointOrBuilder getLoOrBuilder();

  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  boolean hasHi();
  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  com.github.mgljava.grpc.Point getHi();
  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  com.github.mgljava.grpc.PointOrBuilder getHiOrBuilder();
}
