// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/grpc/route_guide.proto

package com.github.mgljava.grpc;

public final class RouteGuideProto {
  private RouteGuideProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_Rectangle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_Rectangle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_FeatureDatabase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_FeatureDatabase_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_RouteNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_RouteNote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_routeguide_RouteSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_routeguide_RouteSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/protobuf/grpc/route_guide.proto\022\nr" +
      "outeguide\",\n\005Point\022\020\n\010latitude\030\001 \001(\005\022\021\n\t" +
      "longitude\030\002 \001(\005\"I\n\tRectangle\022\035\n\002lo\030\001 \001(\013" +
      "2\021.routeguide.Point\022\035\n\002hi\030\002 \001(\0132\021.routeg" +
      "uide.Point\"<\n\007Feature\022\014\n\004name\030\001 \001(\t\022#\n\010l" +
      "ocation\030\002 \001(\0132\021.routeguide.Point\"7\n\017Feat" +
      "ureDatabase\022$\n\007feature\030\001 \003(\0132\023.routeguid" +
      "e.Feature\"A\n\tRouteNote\022#\n\010location\030\001 \001(\013" +
      "2\021.routeguide.Point\022\017\n\007message\030\002 \001(\t\"b\n\014" +
      "RouteSummary\022\023\n\013point_count\030\001 \001(\005\022\025\n\rfea" +
      "ture_count\030\002 \001(\005\022\020\n\010distance\030\003 \001(\005\022\024\n\014el" +
      "apsed_time\030\004 \001(\0052\205\002\n\nRouteGuide\0226\n\nGetFe" +
      "ature\022\021.routeguide.Point\032\023.routeguide.Fe" +
      "ature\"\000\022>\n\014ListFeatures\022\025.routeguide.Rec" +
      "tangle\032\023.routeguide.Feature\"\0000\001\022>\n\013Recor" +
      "dRoute\022\021.routeguide.Point\032\030.routeguide.R" +
      "outeSummary\"\000(\001\022?\n\tRouteChat\022\025.routeguid" +
      "e.RouteNote\032\025.routeguide.RouteNote\"\000(\0010\001" +
      "B2\n\027com.github.mgljava.grpcB\017RouteGuideP" +
      "rotoP\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_routeguide_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_routeguide_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_routeguide_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_routeguide_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_Rectangle_descriptor,
        new java.lang.String[] { "Lo", "Hi", });
    internal_static_routeguide_Feature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_routeguide_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_Feature_descriptor,
        new java.lang.String[] { "Name", "Location", });
    internal_static_routeguide_FeatureDatabase_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_routeguide_FeatureDatabase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_FeatureDatabase_descriptor,
        new java.lang.String[] { "Feature", });
    internal_static_routeguide_RouteNote_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_routeguide_RouteNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_RouteNote_descriptor,
        new java.lang.String[] { "Location", "Message", });
    internal_static_routeguide_RouteSummary_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_routeguide_RouteSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_routeguide_RouteSummary_descriptor,
        new java.lang.String[] { "PointCount", "FeatureCount", "Distance", "ElapsedTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
