// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/grpc/route_guide.proto

package com.github.mgljava.grpc;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.routeguide.Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <code>.routeguide.Point location = 1;</code>
   */
  com.github.mgljava.grpc.Point getLocation();
  /**
   * <code>.routeguide.Point location = 1;</code>
   */
  com.github.mgljava.grpc.PointOrBuilder getLocationOrBuilder();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
